id: ce11f050b9504d2cb8208d4f46e11ef9
initial_creation_type: ocr
source_metadata:
  volumes:
    056d35c7df3b451aac036f401ac125b0:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: ''
      total_pages: 1634
      volume_number: 18
